# PHASE 1 — 공통 Enum 정의 (명세서 10.3)

MAPPING_STATUS = ["CONFIRMED_USER", "INITIAL_MODEL", "BACKTESTED", "DISABLED"]
MAPPING_TYPE = ["DIRECT", "CORE", "INDUSTRY", "THEME"]
WEIGHT_SOURCE = ["DEFAULT_BY_TYPE", "USER_OVERRIDE", "BACKTESTED", "CATALYST_DYNAMIC"]
ASSET_TYPE = ["EQUITY", "ETF", "ADR", "INDEX", "CRYPTO_REFERENCE"]
SCORE_TYPE = ["US_SECTOR", "KOREA_EXPECTED", "KOREA_ACTUAL", "MONEY_FLOW", "LEADER"]

# 명세서 2.2 — Mapping Type별 기본 weight
DEFAULT_WEIGHT_BY_TYPE = {
    "DIRECT": 1.00,
    "CORE": 0.85,
    "INDUSTRY": 0.65,
    "THEME": 0.45,
}

# 명세서 2.1 — 허용된 status 전이만 유효하다.
ALLOWED_STATUS_TRANSITIONS = {
    "INITIAL_MODEL": {"CONFIRMED_USER", "BACKTESTED", "DISABLED"},
    "CONFIRMED_USER": {"BACKTESTED", "DISABLED"},
    "BACKTESTED": {"DISABLED"},
    "DISABLED": set(),
}
